### ISSUE TITLE
Tournament Realm Support

### ISSUE THREAD

**Issue by figyl** [floh22/LeagueBroadcast#3] opened 2021-04-18 13:40 UTC
Since the tournament realm clients don't have /liveclientdata support, levelup/item features don't work.
![image](https://user-images.githubusercontent.com/73833646/115147654-50533d80-a05c-11eb-8624-f78184616757.png)

**Comment by floh22** [comment] 2021-04-20 00:35
Hey. Thanks for the info. I don't have any experience with tournament realm apis. I'll look into the endpoint to see if I can add support

**Comment by floh22** [comment] 2021-04-20 01:06
With what I can gather, tournament realm api has almost everything disabled. If I wanted to add TR support, I would have to use memory reading, something I have very little experience in and it can get messy with anti-cheat. Another option would be to expand LeagueOCR to include level and items, but that is currently not something that I have planned. 

For now I am going to have to disappoint and tell you that level up/items on Tournament Realm cannot be supported at this time

**Comment by availablevic** [comment] 2021-04-20 06:12
Understandable. Thank you for your efforts and keep it up!

**Comment by floh22** [comment] 2021-05-09 00:48
v2 leaves the possiblity for added TR support. Not high on prio list though

**Comment by Freeedooo** [comment] 2022-02-09 08:13
Is there a possibility to put higher on the priority list? I would love to use it on TR as we got some bigger tournaments on the line this year! @floh22

**Comment by floh22** [comment] 2022-02-10 12:50
It's something that I am working on, but I have had to take a step back from the project due to university. I would expect a version with TR support some time this year, but I can't promise anything or even give you a time line of when exactly to expect it.

**Comment by poppaul95** [comment] 2022-02-10 16:05
I am also interested in the TR support, is there a way you can let us know when the version is coming?

**Comment by floh22** [comment] 2022-02-10 16:23
> is there a way you can let us know when the version is coming?

> I would expect a version with TR support some time this year, but I can't promise anything or even give you a time line of when exactly to expect it.

Best way to get informed when this is implemented would be to star the repo or follow this issue

**Comment by poppaul95** [comment] 2022-04-27 17:18
Any updates on this one?

**Comment by Tortron1** [comment] 2022-08-31 11:35
Are any program features supposed or expected to work within tournament realm, or is the program unresponsive to the TR client?
I can't get the program to recognize the TR client as a valid source, and no data seems to be displayed. Is this expected behavior, or should some aspects of the program still function?

**Comment by floh22** [comment] 2023-02-23 22:50
Afaik the ingame api has been enabled on Tournament Realm. This should be fixed

**Closed by floh22** 2023-02-23 22:50 UTC
Labels: bug, low prio
